POST http://localhost:1337/api/auth/local/ HTTP/1.1
content-type: application/json

{
    "identifier": "iannalyanya@gmail.com",
    "password": "Brachiosaurus2020"
}

###
POST http://localhost:1337/api/auth/local/register HTTP/1.1
content-type: application/json

{
    "username": "iannalyanya",
    "password": "Brachiosaurus2020",
    "email": "iannalyanya@gmail.com"
}

###
POST http://localhost:1337/api/auth/local/fcm HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTY2MDMwODg2OSwiZXhwIjoxNjYyOTAwODY5fQ.uMi8t5d5kGGBSIUyc7z7Qqq5lZUn45VJLYWTMR9gBdU


{
    "token": "lmao"

}

###
GET /api/quotes
content-type: application/json
Host: localhost:1337
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU2MzEzODgyLCJleHAiOjE2NTg5MDU4ODJ9.GU_SgzWLURo4oIOmwbufJIY2kTV0mfDpR3SSJIEx9eM

###
POST /api/quotes/
Host: localhost:1337
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU2MzE2MzIxLCJleHAiOjE2NTg5MDgzMjF9.UOWaP09UBDH-wosgxwNnyzNoHraI67v17cXug1ny2lQ
content-type: application/json

{

  "data": {
                "description": "Request Function"
             
            }
}

###
POST /api/likes/
Host: localhost:1337
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU2MzEzODgyLCJleHAiOjE2NTg5MDU4ODJ9.GU_SgzWLURo4oIOmwbufJIY2kTV0mfDpR3SSJIEx9eM
content-type: application/json

{

  "data": {
    "quote": 82

  }
}