// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTTyoYbq8XoXdfftphpVqYLmNL59eOCbo',
    appId: '1:976121777724:web:eec2c8322386e725d0bd39',
    messagingSenderId: '976121777724',
    projectId: 'quotes-7f784',
    authDomain: 'quotes-7f784.firebaseapp.com',
    storageBucket: 'quotes-7f784.appspot.com',
    measurementId: 'G-PQE3PZND2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArm5jcK9b76csVLWuFMusVpNqfJiL5rvE',
    appId: '1:976121777724:android:d963f7ee0438d641d0bd39',
    messagingSenderId: '976121777724',
    projectId: 'quotes-7f784',
    storageBucket: 'quotes-7f784.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6bUXZUGurgNeu581rSE0DX6PLZcxqiU',
    appId: '1:976121777724:ios:d2dba452bf23fd7bd0bd39',
    messagingSenderId: '976121777724',
    projectId: 'quotes-7f784',
    storageBucket: 'quotes-7f784.appspot.com',
    iosClientId: '976121777724-4tvl1t7fj341r55nplf3cronrbsjjtvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
